### ISSUE TITLE
Possible fix for Wiimote extensions not working when game is launched via autoboot

### ISSUE THREAD

**Issue by NintendoManiac64** [niuus/WiiSXRX#17]
Not64 r2021-08-16 (and its subsequent 2021-08-17 hotfix release) added the ability to hot-swap Wiimote extensions while a game is playing which fixed Not64's problem of Wiimote extensions not working when using autoboot + skipmenu unless you unplugged the extension and then returned to the emulator menu (which happens to be the very same behavior that WiiSX RX v2.5 has).

I'm no coding guru (or even a coding amateur), but my best guess is that the following commit is what added that extension hot-swap functionality which subsequently fixed the issue of extensions not working with autoboot:

https://github.com/extremscorner/not64/commit/d7ca5e913f7c3adeb061635a7e68f5e7125e703b#diff-515d9a7589dc16cc8b4da22fdd8bba23732a67fa26bb63081149dcdacfc64e1c

**Comment by niuus** [comment]
> Not64 r2021-08-16 (and its subsequent 2021-08-17 hotfix release) added the ability to hot-swap Wiimote extensions while a game is playing which fixed Not64's problem of Wiimote extensions not working when using autoboot + skipmenu unless you unplugged the extension and then returned to the emulator menu (which happens to be the very same behavior that WiiSX RX v2.5 has).
> 
> I'm no coding guru (or even a coding amateur), but my best guess is that the following commit is what added that extension hot-swap functionality which subsequently fixed the issue of extensions not working with autoboot:
> 
> [extremscorner/not64@d7ca5e9#diff-515d9a7589dc16cc8b4da22fdd8bba23732a67fa26bb63081149dcdacfc64e1c](https://github.com/extremscorner/not64/commit/d7ca5e913f7c3adeb061635a7e68f5e7125e703b#diff-515d9a7589dc16cc8b4da22fdd8bba23732a67fa26bb63081149dcdacfc64e1c)

I mentioned it in the WiiSXRX official thread, but i will check it, sounds interesting for those with the need for this.

**Comment by saulfabregwiivc** [comment]
hi @niuus, i implemented that "small" fix in some of your code, in this pull request: https://github.com/niuus/WiiSXRX/pull/25

Hope this will be added to a new version of WiiSX RX soon.

**Comment by NintendoManiac64** [comment]
I am not sure if this was implemented in v2.6 or not, but the behavior when using a classic controller for example seems identical to v2.5 and therefore the aforementioned issue with autoboot still persists.

It's also possible that this straight-up didn't solve the issue as the theoretical hot-swapping function found in Not64 also seems to not be present, implying that perhaps this was in fact not the corresponding code that handles that function.
